### ISSUE TITLE
Really Bad Core?!


### ISSUE THREAD

**Issue by PocketMiner92** [Milchreisfan/LittleCore#4]
Many things of this "Core" have many Bugs, Not safely tested Things.
You should Test "Youre" Plugins!
Thanks for CodeSteal!!!!!
Its reported to GitHub!!!!!

**Comment by Milchreisfan** [comment]
Code Steal? No bruh a friend (@supercrafter333) helped me. And I know it's not tested because I don't have a testserver rn. But hey buddy report it if you want but it's definitely not a codesteal...

**Comment by supercrafter333** [comment]
Lieber PocketMiner92 (in deinem Profil steht du würdest aus Deutschland kommen, deswegen schreibe ich auch Deutsch),
Könntest du bitte die Fehler aufzählen die die stellen wo Code "geklaut" wurde schicken?

MFG

**Comment by r3pt1s** [comment]
PocketMiner92 bruder selbst wenn der Sourcecode geklaut sein sollte, ist das (no front) nix besonderes wtf?

**Comment by r3pt1s** [comment]
Wenn es aber geklaut sein sollte sende doch mal bitte den Link des "originalen" Github-Projektes hier rein lul

**Comment by PleaseInsertNameHere** [comment]
> PocketMiner92 bruder selbst wenn der Sourcecode geklaut sein sollte, ist das (no front) nix besonderes wtf?

Ist der Quellcode geklaut, kann dies je nach Lizenzvereinbarung ernsthafte Probleme verursachen.

**Comment by r3pt1s** [comment]
Ignorierst du jetzt den Satz "Wenn es aber geklaut sein sollte sende doch mal bitte den Link des "originalen" Github-Projektes hier rein lul" oder was?

**Comment by debugkokichi** [comment]
> Many things of this "Core" have many Bugs, Not safely tested Things.
> You should Test "Youre" Plugins!
> Thanks for CodeSteal!!!!!
> Its reported to GitHub!!!!!

She never stole code, this plugin was all done by her& her friends but if its "stolen" then go on and give us the link to the "actual" one. + Its your not youre,stop emberassing yourself 🤷

**Comment by Milchreisfan** [comment]
Ich glaube nicht das er etwas finden wird. Ich habe keinen CodeSteal begangen, zu dem haben mir Freunde (@supercrafter333, @KinikoYT, @RexFoxina, @Kay313) geholfen. Sollte er es behaupten nur weil es nicht getestet ist dann kann ich auch nicht weiter helfen. Ich habe erwähnt das es **NICHT** getestet ist da mir derzeit die Mittel fehlen.

Schöne Feiertage euch!
